version: "3"

services:
  apiContract:
    image: api-contract-img
    container_name: apiContract
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - zookeeper
      - kafka
    networks:
      - aws-t8-network
  schdeuler:
    image: schdeuler-img
    container_name: scheduler
    depends_on:
      - mongo
      - zookeeper
      - kafka
      - apiContract
    networks:
      - aws-t8-network
  mongo:
    image: mongo:3.6.19-xenial
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - aws-t8-network
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - aws-t8-network
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    networks:
      - aws-t8-network
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
networks:
  aws-t8-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
