GET http://localhost:3000/api/tasks/

###

GET http://localhost:3000/api/tasks/sleep

###

GET http://localhost:3000/api/task/603fddd176ed240de482e550

###

POST http://localhost:3000/api/task
Content-Type: application/json

{
    "timeDelay": "120000",
    "url": "testing call"
}

###

PATCH http://localhost:3000/api/task/604638f1e686aa7ac96266c7
Content-Type: application/json

{
    "timeDelay": "00"
}

###

PATCH http://localhost:3000/api/task/cancel/604e0e4e1e46dc73227b569c
Content-Type: application/json

{
}