GET http://localhost:3000/api/tasks/

###

GET http://localhost:3000/api/tasks/saksham

###

GET http://localhost:3000/api/task/60508a0ae2e1ed3bd0577298

###

POST http://localhost:3000/api/task
Content-Type: application/json

{
    "timeDelay": "12",
    "url": "saksham"
}

###

PATCH http://localhost:3000/api/task/60508a0ae2e1ed3bd0577299
Content-Type: application/json

{
    "timeDelay": "123"
}

###

PATCH http://localhost:3000/api/task/cancel/60508a0ae2e1ed3bd057729c
Content-Type: application/json

{
}